### ISSUE TITLE
Error starting server `npm start` + solution

### ISSUE THREAD

**Issue by btrav** [swoloszynski/journey-planner#27]
Received the following error after running `npm start`:

`SyntaxError: /Users/bentravis/Projects/journey-planner/config/config.json: Unexpected token   in JSON at position 0`

Solution:
Ran old config.json file through https://jsonlint.com/ and came up with:

https://gist.github.com/btrav/a6292bd4a163a9c48ec6cc4b85d8d907

**Comment by swoloszynski** [comment]
I think that the formatting must have gotten messed up when I messaged the configs to you over zoom chat. Glad the linting fixed it. I'm inclined to close the issue since it's now working for both of us, and use the gist file for transferring configs around in the future. 👍
